# Generated by Django 4.1.7 on 2023-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
