# Generated by Django 4.1.6 on 2023-02-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=14)),
                ('dataNascimento', models.DateField()),
                ('dataCadastro', models.DateField(auto_now=True)),
                ('tipoCliente', models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('M', 'Master')], default='F', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=14)),
                ('dataNascimento', models.DateField()),
                ('dataCadastro', models.DateField(auto_now=True)),
                ('tipoFornecedor', models.CharField(choices=[('F', 'F')], default='F', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('qtd', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField()),
                ('validade', models.DateField()),
                ('disponibilade', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.categorias')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.CharField(max_length=14)),
                ('formaPagamento', models.CharField(choices=[('Boleto', 'Boleto'), ('Pix', 'Pix'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito')], default='', max_length=255)),
                ('statusPedido', models.CharField(choices=[('Em Análise', 'Em Análise'), ('Aprovado', 'Aprovado'), ('Negado', 'Negado')], default='Em Análise', max_length=255)),
                ('statusPagamento', models.CharField(choices=[('Em Análise', 'Em Análise'), ('Aprovado', 'Aprovado'), ('Negado', 'Negado')], default='Em Análise', max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.clientes')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
