# Generated by Django 4.1.6 on 2023-02-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedidos')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.produtos')),
            ],
            options={
                'verbose_name_plural': 'Carrinho',
            },
        ),
    ]
