# Generated by Django 4.1.6 on 2023-02-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_pedidoitens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitens',
            old_name='pedido',
            new_name='fkPedido',
        ),
        migrations.RenameField(
            model_name='pedidoitens',
            old_name='produto',
            new_name='fkProduto',
        ),
    ]
