# Generated by Django 4.1.6 on 2023-02-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_remove_pedidoitens_fkpedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitens',
            name='precoAtual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoitens',
            name='qtd',
            field=models.IntegerField(),
        ),
    ]
